version: "3.7"
services:
  # App 1
  app1:
    container_name: knote-app1
    image: learnitguide/knotejs:1.0
    environment:
      MONGO_URL: mongodb://mongo1_db_host:27017/dev
    ports:
      - "80:3000"
    depends_on:
      - mongo1
    links:
      - mongo1:mongo1_db_host
  
  mongo1:
    container_name: knote-mongo1
    image: mongo
  
  # App 2
  app2:
    container_name: knote-app2
    image: learnitguide/knotejs:1.0
    environment:
      MONGO_URL: mongodb://mongo2_db_host:27017/dev
    ports:
      - "81:3000"
    depends_on:
      - mongo2
    links:
      - mongo2:mongo2_db_host
  
  mongo2:
    container_name: knote-mongo2
    image: mongo

  # App 3
  app3:
    container_name: knote-app3
    image: learnitguide/knotejs:1.0
    environment:
      MONGO_URL: mongodb://mongo3_db_host:27017/dev
    ports:
      - "82:3000"
    depends_on:
      - mongo3
    links:
      - mongo3:mongo3_db_host
  
  mongo3:
    container_name: knote-mongo3
    image: mongo
